package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName {{ .Type }} -typeSlug {{ .Slug }}

import "github.com/gopherjs/gopherjs/js"

func (obj *{{ .Type }}) ApplyMatrix(matrix *Matrix4) {
	obj.Call("applyMatrix", matrix)
}

func (obj *{{ .Type }}) Add(m Object3D) {
	obj.Object.Call("add", m)
}

func (obj *{{ .Type }}) Remove(m *js.Object) {
	obj.Object.Call("remove", m)
}

func (obj *{{ .Type }}) GetObjectById(id int) *js.Object {
	return obj.Call("getObjectById", id)
}

// func (obj *{{ .Type }}) Copy() *{{ .Type }} {
// 	return &{{ .Type }}{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *{{ .Type }}) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *{{ .Type }}) getInternalObject() *js.Object {
	return obj.Object
}

func (obj *{{ .Type }}) UpdateMatrix() {
	obj.Call("updateMatrix")
}
