package three
// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName AxesHelper -typeSlug axes_helper

import "github.com/gopherjs/gopherjs/js"

func (obj *AxesHelper) ApplyMatrix(matrix *Matrix4) {
	obj.Call("applyMatrix", matrix)
}

func (obj *AxesHelper) Add(m Object3D) {
	obj.Object.Call("add", m)
}

func (obj *AxesHelper) Remove(m *js.Object) {
	obj.Object.Call("remove", m)
}

func (obj *AxesHelper) GetObjectById(id int) *js.Object {
	return obj.Call("getObjectById", id)
}

// func (obj *AxesHelper) Copy() *AxesHelper {
// 	return &AxesHelper{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *AxesHelper) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *AxesHelper) getInternalObject() *js.Object {
	return obj.Object
}

func (obj *AxesHelper) UpdateMatrix() {
	obj.Call("updateMatrix")
}

