package gthree

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// geometry_method_generator -geometryType CylinderGeometry -geometrySlug cylinder_geometry

import "github.com/gopherjs/gopherjs/js"

var _ Geometry = CylinderGeometry{}

func (g CylinderGeometry) ApplyMatrix4(matrix *Matrix4) {
	g.Object.Call("applyMatrix4", matrix)
}

func (g CylinderGeometry) RotateX() {
	g.Object.Call("rotateX")
}

func (g CylinderGeometry) RotateY() {
	g.Object.Call("rotateY")
}

func (g CylinderGeometry) RotateZ() {
	g.Object.Call("rotateZ")
}

func (g CylinderGeometry) Translate() {
	g.Object.Call("translate")
}

func (g CylinderGeometry) Scale() {
	g.Object.Call("scale")
}

func (g CylinderGeometry) LookAt() {
	g.Object.Call("lookAt")
}

func (g CylinderGeometry) FromBufferGeometry(geometry Geometry) {
	g.Object.Call("fromBufferGeometry")
}

func (g CylinderGeometry) Center() {
	g.Object.Call("center")
}

func (g CylinderGeometry) Normalize() CylinderGeometry {
	g.Object.Call("normalize")
	return g
}

func (g CylinderGeometry) ComputeFaceNormals() {
	g.Object.Call("computeFaceNormals")
}

func (g CylinderGeometry) ComputeVertexNormals(areaWeighted bool) {
	g.Object.Call("computeVertexNormals", areaWeighted)
}

func (g CylinderGeometry) ComputeFlatVertexNormals() {
	g.Object.Call("computeFlatVertexNormals")
}

func (g CylinderGeometry) ComputeMorphNormals() {
	g.Object.Call("computeMorphNormals")
}

func (g CylinderGeometry) ComputeLineDistances() {
	g.Object.Call("computeLineDistances")
}

func (g CylinderGeometry) ComputeBoundingBox() {
	g.Object.Call("computeBoundingBox")
}

func (g CylinderGeometry) ComputeBoundingSphere() {
	g.Object.Call("computeBoundingSphere")
}

func (g CylinderGeometry) Merge(geometry Geometry, matrix Matrix4, materialIndexOffset float64) {
	g.Object.Call("merge", geometry, matrix, materialIndexOffset)
}

func (g CylinderGeometry) MergeMesh(mesh Mesh) {
	g.Object.Call("mergeMesh", mesh.getInternalObject())
}

func (g CylinderGeometry) MergeVertices() {
	g.Object.Call("mergeVertices")
}

func (g CylinderGeometry) SortFacesByMaterialIndex() {
	g.Object.Call("sortFacesByMaterialIndex")
}

func (g CylinderGeometry) ToJSON() interface{} {
	return g.Object.Call("toJSON")
}

// func (g CylinderGeometry) Clone() CylinderGeometry {
// 	return g.Object.Call("clone")
// }

func (g CylinderGeometry) Copy(source Object3D, recursive bool) *CylinderGeometry {
	return &CylinderGeometry{Object: g.getInternalObject().Call("copy", source.getInternalObject(), recursive)}
}

func (g CylinderGeometry) Dispose() {
	g.Object.Call("dispose")
}

func (g CylinderGeometry) getInternalObject() *js.Object {
	return g.Object
}
