package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName PolarGridHelper -typeSlug polargrid_helper

import "github.com/gopherjs/gopherjs/js"

// Compile-time check that this type implements Object3D interface.
var _ Object3D = &PolarGridHelper{}

func (obj *PolarGridHelper) ApplyMatrix4(matrix *Matrix4) {
	obj.Call("applyMatrix4", matrix)
}

func (obj *PolarGridHelper) Add(m Object3D) {
	obj.Object.Call("add", m)
}

func (obj *PolarGridHelper) Remove(m *js.Object) {
	obj.Object.Call("remove", m)
}

func (obj *PolarGridHelper) GetObjectById(id int) *js.Object {
	return obj.Call("getObjectById", id)
}

// func (obj *PolarGridHelper) Copy() *PolarGridHelper {
// 	return &PolarGridHelper{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *PolarGridHelper) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *PolarGridHelper) getInternalObject() *js.Object {
	return obj.Object
}

func (obj *PolarGridHelper) UpdateMatrix() {
	obj.Call("updateMatrix")
}
