package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// material_method_generator -materialName PointsMaterial -materialSlug points_material

import (
	"github.com/fatih/structs"
	"github.com/gopherjs/gopherjs/js"
)

var _ Material = PointsMaterial{}

func (m PointsMaterial) OnBeforeCompile() {
	m.Call("onBeforeCompile")
}

func (m PointsMaterial) SetValues(values MaterialParameters) {
	m.Call("setValues", structs.Map(values))
}

func (m PointsMaterial) ToJSON(meta interface{}) interface{} {
	return m.Call("toJSON", meta)
}

func (m PointsMaterial) Clone() {
	m.Call("clone")
}

func (m PointsMaterial) Copy(source Object3D) {
	m.Call("copy", source)
}

func (m PointsMaterial) Dispose() {
	m.Call("dispose")
}

func (m PointsMaterial) getInternalObject() *js.Object {
	return m.Object
}
