package gthree

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName DirectionalLight -typeSlug directional_light

import "github.com/gopherjs/gopherjs/js"

// Compile-time check that this type implements Object3D interface.
var _ Object3D = &DirectionalLight{}

func (obj *DirectionalLight) ApplyMatrix4(matrix *Matrix4) {
	obj.Call("applyMatrix4", matrix)
}

func (obj *DirectionalLight) Add(m Object3D) {
	obj.Object.Call("add", m)
}

func (obj *DirectionalLight) Remove(m *js.Object) {
	obj.Object.Call("remove", m)
}

func (obj *DirectionalLight) GetObjectById(id int) *js.Object {
	return obj.Call("getObjectById", id)
}

// func (obj *DirectionalLight) Copy() *DirectionalLight {
// 	return &DirectionalLight{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *DirectionalLight) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *DirectionalLight) getInternalObject() *js.Object {
	return obj.Object
}

func (obj *DirectionalLight) UpdateMatrix() {
	obj.Call("updateMatrix")
}
