package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// geometry_method_generator -geometryType ConeGeometry -geometrySlug cone_geometry

import "github.com/gopherjs/gopherjs/js"

func (g ConeGeometry) ApplyMatrix(matrix *Matrix4) {
	g.Object.Call("applyMatrix", matrix)
}

func (g ConeGeometry) RotateX() {
	g.Object.Call("rotateX")
}

func (g ConeGeometry) RotateY() {
	g.Object.Call("rotateY")
}

func (g ConeGeometry) RotateZ() {
	g.Object.Call("rotateZ")
}

func (g ConeGeometry) Translate() {
	g.Object.Call("translate")
}

func (g ConeGeometry) Scale() {
	g.Object.Call("scale")
}

func (g ConeGeometry) LookAt() {
	g.Object.Call("lookAt")
}

func (g ConeGeometry) FromBufferGeometry(geometry Geometry) {
	g.Object.Call("fromBufferGeometry")
}

func (g ConeGeometry) Center() {
	g.Object.Call("center")
}

func (g ConeGeometry) Normalize() ConeGeometry {
	g.Object.Call("normalize")
	return g
}

func (g ConeGeometry) ComputeFaceNormals() {
	g.Object.Call("computeFaceNormals")
}

func (g ConeGeometry) ComputeVertexNormals(areaWeighted bool) {
	g.Object.Call("computeVertexNormals", areaWeighted)
}

func (g ConeGeometry) ComputeFlatVertexNormals() {
	g.Object.Call("computeFlatVertexNormals")
}

func (g ConeGeometry) ComputeMorphNormals() {
	g.Object.Call("computeMorphNormals")
}

func (g ConeGeometry) ComputeLineDistances() {
	g.Object.Call("computeLineDistances")
}

func (g ConeGeometry) ComputeBoundingBox() {
	g.Object.Call("computeBoundingBox")
}

func (g ConeGeometry) ComputeBoundingSphere() {
	g.Object.Call("computeBoundingSphere")
}

func (g ConeGeometry) Merge(geometry Geometry, matrix Matrix4, materialIndexOffset float64) {
	g.Object.Call("merge", geometry, matrix, materialIndexOffset)
}

func (g ConeGeometry) MergeMesh(mesh Mesh) {
	g.Object.Call("mergeMesh", mesh.getInternalObject())
}

func (g ConeGeometry) MergeVertices() {
	g.Object.Call("mergeVertices")
}

func (g ConeGeometry) SortFacesByMaterialIndex() {
	g.Object.Call("sortFacesByMaterialIndex")
}

func (g ConeGeometry) ToJSON() interface{} {
	return g.Object.Call("toJSON")
}

// func (g ConeGeometry) Clone() ConeGeometry {
// 	return g.Object.Call("clone")
// }

func (g ConeGeometry) Copy(source Object3D, recursive bool) *ConeGeometry {
	return &ConeGeometry{Object: g.getInternalObject().Call("copy", source.getInternalObject(), recursive)}
}

func (g ConeGeometry) Dispose() {
	g.Object.Call("dispose")
}

func (g ConeGeometry) getInternalObject() *js.Object {
	return g.Object
}
