package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName Points -typeSlug points

import "github.com/gopherjs/gopherjs/js"

// Compile-time check that this type implements Object3D interface.
var _ Object3D = &Points{}

func (obj *Points) ApplyMatrix4(matrix *Matrix4) {
	obj.Call("applyMatrix4", matrix)
}

func (obj *Points) Add(m Object3D) {
	obj.Object.Call("add", m)
}

func (obj *Points) Remove(m *js.Object) {
	obj.Object.Call("remove", m)
}

func (obj *Points) GetObjectById(id int) *js.Object {
	return obj.Call("getObjectById", id)
}

// func (obj *Points) Copy() *Points {
// 	return &Points{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *Points) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *Points) getInternalObject() *js.Object {
	return obj.Object
}

func (obj *Points) UpdateMatrix() {
	obj.Call("updateMatrix")
}
