package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName ArrowHelper -typeSlug arrow_helper

import "github.com/gopherjs/gopherjs/js"

// Compile-time check that this type implements Object3D interface.
var _ Object3D = &ArrowHelper{}

func (obj *ArrowHelper) ApplyMatrix4(matrix *Matrix4) {
	obj.Call("applyMatrix4", matrix)
}

func (obj *ArrowHelper) Add(m Object3D) {
	obj.Object.Call("add", m)
}

func (obj *ArrowHelper) Remove(m *js.Object) {
	obj.Object.Call("remove", m)
}

func (obj *ArrowHelper) GetObjectById(id int) *js.Object {
	return obj.Call("getObjectById", id)
}

// func (obj *ArrowHelper) Copy() *ArrowHelper {
// 	return &ArrowHelper{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *ArrowHelper) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *ArrowHelper) getInternalObject() *js.Object {
	return obj.Object
}

func (obj *ArrowHelper) UpdateMatrix() {
	obj.Call("updateMatrix")
}
