package gthree

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName Group -typeSlug group

import "github.com/gopherjs/gopherjs/js"

// Compile-time check that this type implements Object3D interface.
var _ Object3D = &Group{}

func (obj *Group) ApplyMatrix4(matrix *Matrix4) {
	obj.Call("applyMatrix4", matrix)
}

func (obj *Group) Add(m Object3D) {
	obj.Object.Call("add", m)
}

func (obj *Group) Remove(m *js.Object) {
	obj.Object.Call("remove", m)
}

func (obj *Group) GetObjectById(id int) *js.Object {
	return obj.Call("getObjectById", id)
}

// func (obj *Group) Copy() *Group {
// 	return &Group{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *Group) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *Group) getInternalObject() *js.Object {
	return obj.Object
}

func (obj *Group) UpdateMatrix() {
	obj.Call("updateMatrix")
}
