package gthree

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// material_method_generator -materialName MeshPhysicalMaterial -materialSlug mesh_physical_material

import (
	"github.com/fatih/structs"
	"github.com/gopherjs/gopherjs/js"
)

var _ Material = MeshPhysicalMaterial{}

func (m MeshPhysicalMaterial) OnBeforeCompile() {
	m.Call("onBeforeCompile")
}

func (m MeshPhysicalMaterial) SetValues(values MaterialParameters) {
	m.Call("setValues", structs.Map(values))
}

func (m MeshPhysicalMaterial) ToJSON(meta interface{}) interface{} {
	return m.Call("toJSON", meta)
}

func (m MeshPhysicalMaterial) Clone() {
	m.Call("clone")
}

func (m MeshPhysicalMaterial) Copy(source Object3D) {
	m.Call("copy", source)
}

func (m MeshPhysicalMaterial) Dispose() {
	m.Call("dispose")
}

func (m MeshPhysicalMaterial) getInternalObject() *js.Object {
	return m.Object
}
