package gthree

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// geometry_method_generator -geometryType {{ .Type }} -geometrySlug {{ .Slug }}

import "github.com/gopherjs/gopherjs/js"

var _ Geometry = {{ .Type }}{}

func (g {{ .Type }}) ApplyMatrix4(matrix *Matrix4) {
	g.Object.Call("applyMatrix4", matrix)
}

func (g {{ .Type }}) RotateX() {
	g.Object.Call("rotateX")
}

func (g {{ .Type }}) RotateY() {
	g.Object.Call("rotateY")
}

func (g {{ .Type }}) RotateZ() {
	g.Object.Call("rotateZ")
}

func (g {{ .Type }}) Translate() {
	g.Object.Call("translate")
}

func (g {{ .Type }}) Scale() {
	g.Object.Call("scale")
}

func (g {{ .Type }}) LookAt() {
	g.Object.Call("lookAt")
}

func (g {{ .Type }}) FromBufferGeometry(geometry Geometry) {
	g.Object.Call("fromBufferGeometry")
}

func (g {{ .Type }}) Center() {
	g.Object.Call("center")
}

func (g {{ .Type }}) Normalize() {{ .Type }} {
	g.Object.Call("normalize")
	return g
}

func (g {{ .Type }}) ComputeFaceNormals() {
	g.Object.Call("computeFaceNormals")
}

func (g {{ .Type }}) ComputeVertexNormals(areaWeighted bool) {
	g.Object.Call("computeVertexNormals", areaWeighted)
}

func (g {{ .Type }}) ComputeFlatVertexNormals() {
	g.Object.Call("computeFlatVertexNormals")
}

func (g {{ .Type }}) ComputeMorphNormals() {
	g.Object.Call("computeMorphNormals")
}

func (g {{ .Type }}) ComputeLineDistances() {
	g.Object.Call("computeLineDistances")
}

func (g {{ .Type }}) ComputeBoundingBox() {
	g.Object.Call("computeBoundingBox")
}

func (g {{ .Type }}) ComputeBoundingSphere() {
	g.Object.Call("computeBoundingSphere")
}

func (g {{ .Type }}) Merge(geometry Geometry, matrix Matrix4, materialIndexOffset float64) {
	g.Object.Call("merge", geometry, matrix, materialIndexOffset)
}

func (g {{ .Type }}) MergeMesh(mesh Mesh) {
	g.Object.Call("mergeMesh", mesh.getInternalObject())
}

func (g {{ .Type }}) MergeVertices() {
	g.Object.Call("mergeVertices")
}

func (g {{ .Type }}) SortFacesByMaterialIndex() {
	g.Object.Call("sortFacesByMaterialIndex")
}

func (g {{ .Type }}) ToJSON() interface{} {
	return g.Object.Call("toJSON")
}

// func (g {{ .Type }}) Clone() {{ .Type }} {
// 	return g.Object.Call("clone")
// }

func (g {{ .Type }}) Copy(source Object3D, recursive bool) *{{ .Type }} {
	return &{{ .Type }}{Object: g.getInternalObject().Call("copy", source.getInternalObject(), recursive)}
}

func (g {{ .Type}}) Dispose() {
	g.Object.Call("dispose")
}

func (g {{ .Type }}) getInternalObject() *js.Object {
	return g.Object
}
